# Generated by Django 5.2.7 on 2025-10-14 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название поля')),
                ('field_key', models.CharField(max_length=50, unique=True, verbose_name='Ключ поля')),
                ('field_type', models.CharField(choices=[('text', 'Текст'), ('email', 'Email'), ('phone', 'Телефон'), ('number', 'Число'), ('date', 'Дата'), ('textarea', 'Многострочный текст')], max_length=20, verbose_name='Тип поля')),
                ('required', models.BooleanField(default=True, verbose_name='Обязательное')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('placeholder', models.CharField(blank=True, max_length=200, verbose_name='Подсказка')),
                ('show_in_list', models.BooleanField(default=True, verbose_name='Показывать в списке')),
            ],
            options={
                'verbose_name': 'Базовое поле',
                'verbose_name_plural': 'Базовые поля',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_data', models.JSONField(default=dict, verbose_name='Базовые данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Человек',
                'verbose_name_plural': 'Люди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonHelpService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_data', models.JSONField(default=dict, verbose_name='Дополнительные данные')),
                ('status', models.CharField(choices=[('active', 'Активно'), ('completed', 'Завершено'), ('pending', 'В ожидании'), ('cancelled', 'Отменено')], default='active', max_length=20, verbose_name='Статус')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Услуга для человека',
                'verbose_name_plural': 'Услуги для людей',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='help_category',
        ),
        migrations.RemoveField(
            model_name='helprequest',
            name='provider',
        ),
        migrations.DeleteModel(
            name='InitialField',
        ),
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['order'], 'verbose_name': 'Дополнительное поле', 'verbose_name_plural': 'Дополнительные поля'},
        ),
        migrations.AlterModelOptions(
            name='helpcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Тип помощи', 'verbose_name_plural': 'Типы помощи'},
        ),
        migrations.AlterModelOptions(
            name='helpprovider',
            options={'verbose_name': 'Поставщик помощи', 'verbose_name_plural': 'Поставщики помощи'},
        ),
        migrations.RemoveField(
            model_name='helpprovider',
            name='help_category',
        ),
        migrations.AddField(
            model_name='helpprovider',
            name='help_categories',
            field=models.ManyToManyField(related_name='providers', to='help.helpcategory', verbose_name='Предоставляемые типы помощи'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Варианты через запятую для полей с выбором', verbose_name='Варианты выбора'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_key',
            field=models.CharField(max_length=50, verbose_name='Ключ поля'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Текст'), ('textarea', 'Многострочный текст'), ('email', 'Email'), ('phone', 'Телефон'), ('number', 'Число'), ('choice', 'Выбор из списка'), ('date', 'Дата'), ('checkbox', 'Галочка')], max_length=20, verbose_name='Тип поля'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='help_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='help.helpcategory', verbose_name='Тип помощи'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название поля'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Подсказка'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Обязательное'),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='icon',
            field=models.CharField(default='help', max_length=50, verbose_name='Иконка'),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='helpprovider',
            name='bio',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AlterField(
            model_name='helpprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='helpprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='person',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_people', to='help.helpprovider', verbose_name='Добавил'),
        ),
        migrations.AddField(
            model_name='personhelpservice',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_services', to='help.helpprovider', verbose_name='Добавил услугу'),
        ),
        migrations.AddField(
            model_name='personhelpservice',
            name='help_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='help.helpcategory', verbose_name='Тип помощи'),
        ),
        migrations.AddField(
            model_name='personhelpservice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_services', to='help.person', verbose_name='Человек'),
        ),
        migrations.DeleteModel(
            name='HelpRequest',
        ),
        migrations.AlterUniqueTogether(
            name='personhelpservice',
            unique_together={('person', 'help_category')},
        ),
    ]
