# Generated by Django 5.2.7 on 2025-10-16 13:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0002_basefield_person_personhelpservice_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basefield',
            options={'ordering': ['order'], 'verbose_name': 'Câmp de bază', 'verbose_name_plural': 'Câmpuri de bază'},
        ),
        migrations.AlterModelOptions(
            name='customfield',
            options={'ordering': ['order'], 'verbose_name': 'Câmp suplimentar', 'verbose_name_plural': 'Câmpuri suplimentare'},
        ),
        migrations.AlterModelOptions(
            name='helpcategory',
            options={'ordering': ['order', 'name'], 'verbose_name': 'Tip de ajutor', 'verbose_name_plural': 'Tipuri de ajutor'},
        ),
        migrations.AlterModelOptions(
            name='helpprovider',
            options={'verbose_name': 'Furnizor de ajutor', 'verbose_name_plural': 'Furnizori de ajutor'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'ordering': ['-created_at'], 'verbose_name': 'Persoană', 'verbose_name_plural': 'Persoane'},
        ),
        migrations.AlterModelOptions(
            name='personhelpservice',
            options={'ordering': ['-created_at'], 'verbose_name': 'Serviciu pentru persoană', 'verbose_name_plural': 'Servicii pentru persoane'},
        ),
        migrations.AlterField(
            model_name='basefield',
            name='field_key',
            field=models.CharField(max_length=50, unique=True, verbose_name='Cheie câmp'),
        ),
        migrations.AlterField(
            model_name='basefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Telefon'), ('number', 'Număr'), ('date', 'Dată'), ('textarea', 'Text pe mai multe rânduri')], max_length=20, verbose_name='Tip câmp'),
        ),
        migrations.AlterField(
            model_name='basefield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nume câmp'),
        ),
        migrations.AlterField(
            model_name='basefield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordine'),
        ),
        migrations.AlterField(
            model_name='basefield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sugestie'),
        ),
        migrations.AlterField(
            model_name='basefield',
            name='required',
            field=models.BooleanField(default=True, verbose_name='Obligatoriu'),
        ),
        migrations.AlterField(
            model_name='basefield',
            name='show_in_list',
            field=models.BooleanField(default=True, verbose_name='Afișare în listă'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='choices',
            field=models.TextField(blank=True, help_text='Variante separate prin virgulă pentru câmpuri cu alegere', verbose_name='Variante de alegere'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_key',
            field=models.CharField(max_length=50, verbose_name='Cheie câmp'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text pe mai multe rânduri'), ('email', 'Email'), ('phone', 'Telefon'), ('number', 'Număr'), ('choice', 'Alegere din listă'), ('date', 'Dată'), ('checkbox', 'Bifă')], max_length=20, verbose_name='Tip câmp'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='help_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='help.helpcategory', verbose_name='Tip de ajutor'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nume câmp'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordine'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='placeholder',
            field=models.CharField(blank=True, max_length=200, verbose_name='Sugestie'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='required',
            field=models.BooleanField(default=False, verbose_name='Obligatoriu'),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='description',
            field=models.TextField(blank=True, verbose_name='Descriere'),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='icon',
            field=models.CharField(default='help', max_length=50, verbose_name='Pictogramă'),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='helpcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Ordine'),
        ),
        migrations.AlterField(
            model_name='helpprovider',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Despre mine'),
        ),
        migrations.AlterField(
            model_name='helpprovider',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data înregistrării'),
        ),
        migrations.AlterField(
            model_name='helpprovider',
            name='help_categories',
            field=models.ManyToManyField(related_name='providers', to='help.helpcategory', verbose_name='Tipuri de ajutor oferite'),
        ),
        migrations.AlterField(
            model_name='helpprovider',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Utilizator'),
        ),
        migrations.AlterField(
            model_name='person',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_people', to='help.helpprovider', verbose_name='Adăugat de'),
        ),
        migrations.AlterField(
            model_name='person',
            name='base_data',
            field=models.JSONField(default=dict, verbose_name='Date de bază'),
        ),
        migrations.AlterField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data adăugării'),
        ),
        migrations.AlterField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data actualizării'),
        ),
        migrations.AlterField(
            model_name='personhelpservice',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_services', to='help.helpprovider', verbose_name='Serviciu adăugat de'),
        ),
        migrations.AlterField(
            model_name='personhelpservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data adăugării'),
        ),
        migrations.AlterField(
            model_name='personhelpservice',
            name='custom_data',
            field=models.JSONField(default=dict, verbose_name='Date suplimentare'),
        ),
        migrations.AlterField(
            model_name='personhelpservice',
            name='help_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='help.helpcategory', verbose_name='Tip de ajutor'),
        ),
        migrations.AlterField(
            model_name='personhelpservice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Notițe'),
        ),
        migrations.AlterField(
            model_name='personhelpservice',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_services', to='help.person', verbose_name='Persoană'),
        ),
        migrations.AlterField(
            model_name='personhelpservice',
            name='status',
            field=models.CharField(choices=[('active', 'Activ'), ('completed', 'Finalizat'), ('pending', 'În așteptare'), ('cancelled', 'Anulat')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='personhelpservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data actualizării'),
        ),
    ]
