# Generated by Django 5.2.7 on 2025-10-16 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0003_alter_basefield_options_alter_customfield_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basefield',
            name='choices',
            field=models.TextField(blank=True, help_text='Variante separate prin virgulă pentru câmpuri tip "Alegere din listă"', verbose_name='Variante de alegere'),
        ),
        migrations.AlterField(
            model_name='basefield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('email', 'Email'), ('phone', 'Telefon'), ('number', 'Număr'), ('date', 'Dată'), ('textarea', 'Text pe mai multe rânduri'), ('select', 'Alegere din listă')], max_length=20, verbose_name='Tip câmp'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('textarea', 'Text pe mai multe rânduri'), ('email', 'Email'), ('phone', 'Telefon'), ('number', 'Număr'), ('choice', 'Alegere din listă'), ('date', 'Dată'), ('checkbox', 'Bifa')], max_length=20, verbose_name='Tip câmp'),
        ),
    ]
